name: Fetch Data and Upload CSV

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Enables manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the Python script
        run: |
          python fetch-data.py

      - name: Set Git Identity
        run: |
          git config --global user.email "gamingnotch4u@gmail.com"
          git config --global user.name "GaamaAala"

      - name: Commit and push updated CSV file
        run: |
          git add data.csv
          git commit -m "Update data.csv with latest results" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
